### ISSUE TITLE
Wouldn't it make sense to separate  binary I/O and serialization

### ISSUE THREAD

**Issue by MikeGitb** [Lyberta/cpp-io#2]
I've only read through your README, but wouldn't it make sense to split up binary i/o (reading/writing e.g. into/from a `std::span<std::byte>` or a stream of `std::bytes` as efficiently as possible) and serialization (deciding on how Foo should be represented when stored outside of the program (be it on disk, on the network or in a different program).

I'd really love to have a standardized low level binary interface that is decoupled from all the text-focused iostream abominations (essentially a c++ version of the simple POSIX open/ close/ read/write API). I am a bit worried though,  that this relative straight forward part (yes,  I know that when you look into the details it becomes not all that simple anymore) will get delayed and dragged down by endless discussions in the committee about what exactly `std::io::write(stream,Foo{1,2})` should do by default.

**Comment by Lyberta** [comment]
That is why out-of-the-box `std::io::write` supports only `std::byte`, `bool`, integers, enums, floating point and `std::span<std::byte>` because there is not much ways to serialize them and `std::io::format` handles all important ones.

The rest is up to the user.

**Comment by MikeGitb** [comment]
> because there is not much ways to serialize them

I can think of a lot of different ways.  Starting with things like endianess and alignment, and not ending with compression (e.g. something simple as putting agent bills into a bitfield) and encryption. I also don't see a reason, why the iso-c++ standard should bake a particular default format for serialized data into stone (that's the domain of file formats and protocol standards) and if it doesn't,  it is all but useless to me because then I'm loosing portability over time and space (which is usually exactly what I try to bridge with I/O).

I think my more fundamental concern is that (a) storing raw bytes and (b) encoding even fundamental data types into raw bytes are two orthogonal problems and  imho should not be mixed in the same API (that is one of the problems with iostrems).

Also, from an efficiency perspective,  I'm not sure if storing the format options as part of the I/O object is ideal, when the desired format will - most of the time - be known at compile time, but that is just a side note.

**Comment by Lyberta** [comment]
> > because there is not much ways to serialize them
> 
> I can think of a lot of different ways.

Sure but in my experience most formats use two's complement integers and IEEE floats and store them in `std::memcpy`-like fashion so, for example C code could use casts and read data directly. Of course, C++ object model is more difficult and this doesn't work here at least as of C++17.

I've tried to cover the most common cases with `std::io::format` while giving users the freedom to do all the corner cases themselves. In particular, if you want custom serialization format for an object, you'd probably want to put this thing in a dedicated class and there you can define `read` and `write` member functions that can do all the bit fiddling you want.

> Starting with things like endianess and alignment

RIFF example shows how to handle both. It has runtime endianness based on first 4 bytes and 16 bit alignment for chunks.

> and not ending with compression (e.g. something simple as putting agent bills into a bitfield) and encryption.

I guess some encryption can be transparently done with the current API. It just requires a stream class that does encryption in `write_some` member function. Something as densely packed as bitfields would probably need to put into a separate class unless you're talking about packing everything. That... hmm, I've never seen formats like this.

> I also don't see a reason, why the iso-c++ standard should bake a particular default format for serialized data into stone

Because `std::memcpy`-like semantics are the fastest so it's a good idea to expose those. Other stuff is added so users don't need to reinvent obvious wheels such as endianness conversion (which is pretty impossible to write 100% portably for floating point).

> (that's the domain of file formats and protocol standards) and if it doesn't, it is all but useless to me because then I'm loosing portability over time and space (which is usually exactly what I try to bridge with I/O).

You are free to write custom classes for any format you want.

> I think my more fundamental concern is that (a) storing raw bytes and (b) encoding even fundamental data types into raw bytes are two orthogonal problems and imho should not be mixed in the same API (that is one of the problems with iostrems).

Sure, I can split `std::io::write` into `std::io::write` for bytes and `std::io::serialize` for serialization. But I feel that `std::io::serialize` is a bit mouthful to write and both cases can be distinguished enough considering I never use such type breaking things like `void*`. You have to explicitly pass `std::span<std::byte>` or something convertible such as `std::vector<std::byte>` for raw IO. Also, there is a [separate proposal for low-level IO](https://wg21.link/p1031) if you want 100% performance.

> Also, from an efficiency perspective, I'm not sure if storing the format options as part of the I/O object is ideal, when the desired format will - most of the time - be known at compile time, but that is just a side note.

Most of the time, but not always. If I split `std::io::format` outside of stream class then all `read` and `write` member functions will have to take it explicitly or I will need some complex logic for 1 and 2 argument versions. And you still need endianness conversion anyway for portable code. This can be discussed further.

My plan is to present this as a paper in Prague so if the committee feels like some of the suggestions are desired, I can tweak the API.

**Comment by MikeGitb** [comment]
> Sure, I can split std::io::write into std::io::write for bytes and std::io::serialize for serialization. 

You probably misunderstand me:  I'm not just talking about giving different  names to different overloads, but a vertical split into two layers: `serialize` should not do any I/O and `write` should not do any serialization. I might want to send the serialized data to something completely different than a std::io::filestream (sorry, on my mobile, so I haven't looked up the actual name) and I might want to use my own serialization logic with your filestream. Again, talking to an I/O device and deciding  on a "wire-format" are two completely independent issues. The APIs should be designed to easily and efficiently compose,  but one should not imply the other.

Anyway, if I haven't convinced you so far,  I don't think I will. Looking forward to see how the paper evolves.  Thanks for listening.

**Comment by Lyberta** [comment]
Then what would `serialize` do? What would be the result? Right now if you want to serialize to memory you just `write` to `span_stream` or `memory_stream`. But obviously serializing to `memory_stream` most likely will result in dynamic allocations. You can `write` to `file_stream` without any memory allocations in many cases.

**Comment by MikeGitb** [comment]
> Then what would serialize do? What would be the result? 

Two obvious choices: Either you pass in something that satisfies a "buffer" or stream concept as a parameter (and your streams may or may not satisfy that concept), or - for small types like the ones you are considering: You return an array of bytes. Neither option requires dynamic memory allocation.

I don't know,  what the "right" answer here is - serialization is a complex topic with many possible design tradeoffs. That's why I think it should not be mixed with I/O on the standard library level. 

To be honest: Most of the time I anyway either need a full blown serialization protocol/library like protobuf or I just want to write the in memory representation of my pods as efficiently as possible. Writing individual numbers in a standardized format to io just doesn't happen all that often.

**Comment by Lyberta** [comment]
Current design is still in the spirit of iostreams. You do
```
std::cout << 42;
```
Not
```
std::vector<char> buffer;
std::textify(buffer, 42);
std::cout << buffer;
```

One might argue that we now have `std::format` as our version of hypothetical `std::textify` but I'd say it was born of desire to solve a narrow problem.

I think not having explicit serialization step works in practice. It worked for all my use cases. And considering that people who understand iostream's `operator<<` can easily learn that `std::io::write` is a same thing just for raw bytes, I think it will be easy to teach.

Niall Douglas who is the person in charge of LLFIO and low level parts of Networking TS also initially thought that having explicit serialization step is a good idea but then decided to agree with me so far, at least for the higher-level API that this paper proposes.

**Comment by MikeGitb** [comment]
If you want a simple way to write 42 to a binary output, you can write `write(stream, view_bytes(42))`. If you are writing to a binary output, we are far beyond "I just want to quickly display the value of variable x in a human readable form", which is what `cout << x` does.  Instead, you usually either want to make a quick memory dump (either for later inspection or for efficient communication on a single platform) or you want to adhere to some particular binary protocol.  In neither of those two situations is a standardized, but c++ specific encoding for ints really useful. 

Well,  doesn't matter. Intelligent people can disagree.  Also, I'm not involved in the standardization process,  so my opinion doesn't really count more than that of any other random guy on the internet and luckily, writing a stream wrapper for posix binary I/O myself is really not hard,  so I'm not too worried if and in what form your streams will get into the standard. 

Again,  best of luck.

**Comment by Lyberta** [comment]
FYI, I did separate raw unformatted IO from serialization because I had problems implementing nested streams such as buffered files or type erased streams in consistent way.

Looks like iostreams got almost everything wrong design-wise.
